---
- hosts: all
  become: yes
  vars:
    ansible_distribution_release: "focal"
  tasks:
    - name: Changing mirrors
      replace:
        path: /etc/apt/sources.list
        regexp: 'http://archive.ubuntu.com/ubuntu'
        replace: 'http://ru.archive.ubuntu.com/ubuntu'
        backup: yes

    - name: Full system upgrade
      become: yes
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install CLI apps and libraries
      apt:
        name:
          - build-essential
          - software-properties-common
          - make
          - htop
          - iotop
          - rsync
          - atop
        state: latest

    - name: Atop configuration
      replace:
        path: /usr/share/atop/atop.daily
        regexp: 'INTERVAL=\d+'
        replace: 'INTERVAL=1'
        backup: yes

    - name: Restart Atop service, in all cases
      service:
        name: atop
        state: restarted
    
    - name: Install the gpg key for MongoDB
      apt_key:
        url: "https://www.mongodb.org/static/pgp/server-5.0.asc"
        state: present

    - name: Install the MongoDB repos
      apt_repository:
        repo: "deb https://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/5.0 multiverse"
        state: present
        update_cache: yes

